graph TD
    subgraph 越后期概率越大
    D[/看心情\]
    E([拦])
    C([不拦])
    H[/看心情\]
    J[/看性格\]
    I([不拦])
    end
    A{自己是？} -->|神秘人| B{要赢的人是？} -->|神秘人| M([不拦])
    B -->|阵营方| D -->|大概率| E
    D -->|小概率| C
    A -->|阵营方| F{要赢的人是？} -->|神秘人| H -->|大概率| J -->|50%激进型| K[防所有神秘人任务]
    F -->|对方阵营方| G([拦])
    J -->|50%保守型| L[正常拦]
    H -->|小概率| I